### PR TITLE
Add icicle plots

### PR DESCRIPTION
**Pull request by yxiong**
I tried to make this commit in the least intrusive way (with minimum modification to the existing code), for your convenience to review. I'd be happy to do a refactoring afterwards, if you feel this addition useful. Thanks.

### CODE REVIEW

**Comment by jiffyclub** [comment]
Thanks for getting started on this! This looks great and I'd love to have icicle plots supported. How are you thinking of refactoring things?

This is what it looks like on my 13" laptop:

screenshot 2015-04-01 19 35 05

And with info displayed:

screenshot 2015-04-01 19 41 43

**Comment by yxiong** [comment]
I'm glad you like this commit.

For the refactoring, I will probably move some chunk of code around to remove redundancy, and maybe rename `sunburst.js` to `drawsvg.js`. I also plan to modify the CSS to move `info` and `svg` around for different plot styles, in order to eliminate overlap.

Anyway, let me take a stab. Will check in another version soon.

**Comment by jiffyclub** [comment]
Sounds good, thanks!

**Comment by yxiong** [comment]
Done.

I am a D3 and CSS beginner though. Feel free to let me know how you like it or make any changes as you see appropriate.

**Comment by jiffyclub** [comment]
Thanks! You can't be any more of a D3 and CSS beginner than me. :smile: 

It looks like the info div is narrower than necessary in sunburst mode:

screenshot 2015-04-01 21 49 43

I've currently got the width of that div being set dynamically so it can be as big as possible without running into the visualization. That was here: https://github.com/jiffyclub/snakeviz/pull/53/files#diff-197f8594da4f4b7e69f64d3d77ce350eL145 What do you think about doing the sizing that way?

**Comment by yxiong** [comment]
Yep, that makes sense. I was using a tall browser window and therefore didn't notice it. Just checked in a commit to fix this.

**Comment by embray** [comment]
:+1: This change also reveals a few areas that could be refactored to better support adding new plot types in the future, but good enough for now.

**Comment by jiffyclub** [comment]
There are still some layout issues on my 13" screen:

screenshot 2015-04-02 08 34 33

screenshot 2015-04-02 08 34 48

If you like, I can take a crack at fixing those up later.

**Comment by embray** [comment]
Is the issue just that the info div pops over to the top of the plot instead of to the left?

**Comment by jiffyclub** [comment]
Also that in sunburst mode when the info div flows over the plot it flickers on mouse move, but that might be related.

**Comment by jiffyclub** [comment]
I'm not sure I like having the controls above the icicle plot, it's really awkward on my 13" screen. So I'd also like to experiment with keeping the same layout for both plot types.

**Comment by jiffyclub** [comment]
@yxiong, I've made a PR on your branch at yxiong/snakeviz#1 with some updates that take care of things for me. End result is that it looks like this:

screenshot 2015-04-02 12 14 31

Let me know if that works for you, especially on a bigger screen.

**Comment by yxiong** [comment]
Merged. Thanks, @jiffyclub!

**Comment by jiffyclub** [comment]
Great! Thanks again for taking this on, an alternative to the sunburst has been an oft requested feature.

**Pull request merged**
