### PR TITLE
Add support for Python 3.12 and drop EOL 3.7

### PR DESCRIPTION
**Pull request by hugovk**
Also upgrade Python syntax using https://github.com/asottile/pyupgrade and remove some old Python 2 imports and unused things.

### CODE REVIEW

**Comment by alex77g2** [comment]
it would be nice if snakeviz would be usable also in PYthon 3.12. IS there any release planned?

**Comment by hugovk** [comment]
@jiffyclub Hello, any interest in this?

Since I opened this, Python 3.13 has also been released and 3.8 dropped, but would be good to get this merged first. Thank you!

**Comment by jiffyclub** [comment]
Looks good, thank you!

**Comment by hugovk** [comment]
Thanks! 

Here's the followup to add 3.13 and drop 3.8: https://github.com/jiffyclub/snakeviz/pull/199

**Pull request merged**
