### PR TITLE
Clean up sv_build_hierarchy, fix issue #72

### PR DESCRIPTION
**Pull request by nschloe**
Starting out as a cleanup of `sv_build_hierarchy`, this PR actually fixes issue #72.

### CODE REVIEW

**Comment by nschloe** [comment]
For the sake of completeness, here's a before/after:

b


f

**Comment by jiffyclub** [comment]
Thanks for this! As far as I can tall the mode sizing is now more consistent with the reported times.

It looks like this changed the behavior of the "cutoff". Before:
image

After:
image

I don't have super strong feelings on that, but it is a different behavior. Maybe because it looks like your update doesn't add nodes that fall under the threshold, while previously the nodes would be added, but not recursed into?

The treatment of recursion is definitely different. Before:
image

After:
image

I've also noticed some weirdness around performance. In some situations this PR performs better than master (possibly because of the stricter interpretation of cutoff) and in others this PR performs much worse, such that I can't even zoom into a part of a profile can easily be examined on master (likely related to the differing treatments of recursion, e.g. there is recursion in the parts of the call stack I'm trying to zoom into).

**Comment by nschloe** [comment]
Thanks @jiffyclub for the review.

I've added a few commits that should improve the situation for the recursion.

**Comment by nschloe** [comment]
@jiffyclub Ping.

**Comment by jiffyclub** [comment]
Sorry for being unresponsive on here, I'm hoping to get in another review of this in the next week. I have some test profiles that look quite different with this update and I'm thinking on whether the changes make sense. I might post some here for your thoughts.

**Comment by jiffyclub** [comment]
Hi, sorry for the slowness here. Thanks for bearing with me. There is still a difference between master and this PR when it comes to recursion:

Before:
image

After:
image

(That's using [this profile](https://www.dropbox.com/s/04kydfkjqqb689e/sleep_recurse2.prof?dl=0), requires Python 2.)

Another thing I'm looking at is this profile, but the difference isn't particularly actionable:

Before:
image

After:
image

Recursion shows up again, but it actually shows up in master too, but you can't see it because it's tiny in the graph. I don't have a ton of thoughts about this one because the numbers are clearly a bit strange. (Total run time is 4 seconds, but total run time of the two tasks immediately below the root report as 8 seconds. I think the flow of this call graph makes things look weird.) The graph produced by this PR is totally reasonable given the numbers, but I think the graph produced by master is a more reasonable reflection of reality, but it's kind of an accident? I wouldn't block this PR based on this change since I think this particular profile is a tough one.

**Comment by kenahoo** [comment]
What's the latest thought about this?

**Comment by jiffyclub** [comment]
@kenahoo Are you using this branch? Do you have any feedback? At this point I still consider this PR to have a regression when it comes to displaying recursion, so I'm not ready to merge it.

**Comment by nschloe** [comment]
Tuning in.

It's been a while since I submitted this thing, and frankly I forgot how to get set up for testing. It'll take a while before I get back to it.

As for displaying recursion, I'd say the best approach is to display what actually happens. If a recursive call of `myfun()` takes 50% of the time of `myfun()` (the parent), it should probably be displayed this way. If @jiffyclub's example from above is actually an example like this I can't tell; the sources aren't disclosed.

As shown at the very beginning, this PR fixes a significant issue, one that I'd vote above many other things: The current master distorts the proportions, and sometimes to a large degree, which almost defeats the purpose of the tool.

Anyhow. I'll try to make some time to get building and testing set up again.

**Comment by jiffyclub** [comment]
The challenge with the recursive calls is that displaying it as an infinite nested series is misleading (we don't actually know how many recursive calls there were) and it can negatively affect performance by adding a lot of nodes to the SVG (that don't necessarily contain information). That said, snakeviz might not be showing recursion in a natural way right now either.

**Comment by nschloe** [comment]
@jiffyclub Thanks for the comment.

I've downloaded the recursion profile you posted above, and I can reproduce what you see. Without the source code, however, I cannot tell what's wrong with it.

**Comment by jiffyclub** [comment]
I tried digging around for the source code but I made that so long ago that I think I've lost track of it. But I was able to come up with a new example, here's the source:

```py
import time


def sleep1():
    time.sleep(0.1)


def sleep3():
    for _ in range(3):
        sleep1()


def sleep_intermediate(times, recurse=False):
    sleep1()
    sleep_recurse(times, recurse=recurse)


def sleep_recurse(times, recurse=False):
    sleep1()

    if recurse:
        sleep_intermediate(times, recurse=False)
    else:
        for _ in range(times):
            sleep1()


def main():
    sleep3()
    sleep_recurse(times=2, recurse=True)


if __name__ == '__main__':
    main()
```

And here's the output I see with this branch on my computer with Python 3.6:

image

I also made an example where the `sleep_recurse` function recurses by calling itself and in that case I don't see the infinite recursion in the visualization. So it seems to happen only when there's some intermediary function. Here's that source:

```py
import time


def sleep1():
    time.sleep(0.1)


def sleep3():
    for _ in range(3):
        sleep1()


def sleep_recurse(times, recurse=False):
    sleep1()

    if recurse:
        sleep_recurse(times, recurse=False)
    else:
        for _ in range(times):
            sleep1()


def main():
    sleep3()
    sleep_recurse(times=2, recurse=True)


if __name__ == '__main__':
    main()
```

**Comment by nschloe** [comment]
Thanks for merging!

**Comment by jiffyclub** [comment]
Thanks for your work on this! I ended up re-implementing the previous call-stack tracking within your changes to avoid displaying recursion (see 700ad9612c716af40f7f6b8257cd644f19486ea6). This has been released in version 0.4.2.

**Pull request merged**
